spring:
  application:
    name: user-service
  # 默认 dev 环境
  profiles:
    active: dev
##  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yubi?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: zc
  redis:
    database: 1
    host: 1.92.81.128
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
#  rabbitmq:
#    host: 192.168.92.250
#    port: 5672
#    password: guest
#    username: guest
server:
  address: 0.0.0.0
  port: 8082
  servlet:
    context-path: /
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://1.92.81.128:2181
    timeout: 22000
  protocol:
    name: dubbo
    port: 20890
  scan:
    base-packages: com.zccc.service
