spring:
  application:
    name: eureka-server01
server:
  port: 8761 # Eureka Server 默认端口号

eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://localhost:8764/eureka
  instance:
    hostname: eureka-server-01
