spring:
  application:
    name: nacos
  cloud:
    nacos:
      discovery:
        server-addr: http://1.92.81.128:8848
      config:
        server-addr: http://1.92.81.128:8848
        enabled: false
server:
  port: 8761


